### ISSUE TITLE
Padrão Rest

### ISSUE THREAD

**Issue by imed-pedrosantos** [conexasaude/imed-back-end#12]
Não está seguindo o padrão Rest. 

https://github.com/conexasaude/imed-back-end/blob/916e29e8988a77a57af14279e5843ea64f0d7e61/src/main/java/com/end/beck/desafio/imedback/Controllers/AttendanceController.java#L23

**Comment by cnx-danielves** [comment]
https://mari-azevedo.medium.com/construindo-uma-api-restful-com-java-e-spring-framework-46b74371d107

**Comment by cnx-danielves** [comment]
Realizado ajuste no attendance controle da estrutura rest

**Comment by cnx-danielves** [comment]
ajustado
