### ISSUE TITLE
Repository nos controller

### ISSUE THREAD

**Issue by imed-pedrosantos** [conexasaude/imed-back-end#14]
Dessa forma vc está salva diretamente no banco sem passar por uma camada de regra de negócio. 

https://github.com/conexasaude/imed-back-end/blob/916e29e8988a77a57af14279e5843ea64f0d7e61/src/main/java/com/end/beck/desafio/imedback/Controllers/AttendanceController.java#L27

**Comment by cnx-danielves** [comment]
repository movido para o serviceImpl
