### ISSUE TITLE
@Autowired

### ISSUE THREAD

**Issue by imed-pedrosantos** [conexasaude/imed-back-end#15]
Entender como spring faz a gestão dessa dependência. 

https://github.com/conexasaude/imed-back-end/blob/916e29e8988a77a57af14279e5843ea64f0d7e61/src/main/java/com/end/beck/desafio/imedback/Controllers/AttendanceController.java#L26

**Comment by cnx-danielves** [comment]
o @Autowired faz a injeção de dependência, sendo assim é um forma diferente de realizar a instância de um objeto , fazendo que nesse contexto a classe controladora controle o objeto dependente.

**Comment by cnx-danielves** [comment]
como foi comentando em nossa reunião por segurança não podemos retornar nossas classe por completo pois assim , quem tiver acesso a esse dados podem descobrir como é feito nossa estrutura e invadir nosso sistema

**Comment by cnx-danielves** [comment]
então a solução seria injetar as classes do onde possui os repository com jpa em nossos ServiceImp para ter mais segurança e retirar a regras de negócios dos controllers.
