### ISSUE TITLE
Padrão REST

### ISSUE THREAD

**Issue by imed-pedrosantos** [conexasaude/imed-back-end#21]
Não utilizar camelCase.
https://github.com/conexasaude/imed-back-end/blob/753c018e3e9f610b4fe17b62dc74c88f93f68eb7/src/main/java/com/end/beck/desafio/imedback/Controllers/HealthcareProfessionalController.java#L22

**Comment by imed-pedrosantos** [comment]
oi

**Comment by cnx-danielves** [comment]
correção do findById no repository, agora estou utilizando o nativo do spring;
